---
sudo: required

language: python

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - qemu-utils

before_install:
  - openssl aes-256-cbc -K $encrypted_1bfa3291317c_key -iv $encrypted_1bfa3291317c_iv -in clouds.yml.enc -out clouds.yml -d

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - yamllint -c .yamllint.yml .
  - travis_wait 30 python images.py

notifications:
  irc:
    channels:
      - "irc.freenode.org#betacloud"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
